const dishStyles = ['French', 'Spanish', 'Portuguese', 'Greek', 'Turkish', 'Moroccan', 'Tunisian', 'Egyptian', 'Lebanese', 'Syrian', 'Israeli', 'Persian', 'Georgian', 'Armenian', 'Azerbaijani', 'Russian', 'Ukrainian', 'Polish', 'Czech', 'Hungarian', 'Romanian', 'Bulgarian', 'Serbian', 'Croatian', 'Bosnian', 'Slovenian', 'Albanian', 'Macedonian', 'Swiss', 'Austrian', 'German', 'Belgian', 'Dutch', 'British', 'English', 'Scottish', 'Welsh', 'Irish', 'Scandinavian', 'Norwegian', 'Swedish', 'Danish', 'Finnish', 'Icelandic', 'Estonian', 'Indian', 'Lithuanian', 'Mediterranean', 'Balkan', 'Catalan', 'Basque', 'Andalusian', 'Tuscan', 'Roman', 'Neapolitan', 'Sicilian', 'Venetian', 'Ligurian', 'Piedmontese', 'Lombard', 'Calabrian', 'American', 'Californian', 'Texan', 'Tex-Mex', 'Southern', 'Cajun', 'Creole', 'Hawaiian', 'Mexican', 'Yucatecan', 'Oaxacan', 'Peruvian', 'Brazilian', 'Argentinian', 'Chilean', 'Colombian', 'Venezuelan', 'Ecuadorian', 'Uruguayan', 'Caribbean', 'Jamaican', 'Cuban', 'Dominican', 'Chinese', 'Cantonese', 'Sichuan', 'Hunan', 'Shanghainese', 'Taiwanese', 'Japanese', 'Okinawan', 'Korean', 'Thai', 'Vietnamese', 'Cambodian', 'Laotian', 'Malaysian', 'Singaporean', 'Indonesian'];
const whatAddeds = ['truffle', 'porcini', 'chanterelle', 'morel', 'shiitake', 'oyster', 'portobello', 'cremini', 'enoki', 'lobster', 'crab', 'shrimp', 'prawn', 'scallop', 'clam', 'mussel', 'octopus', 'squid', 'cuttlefish', 'tuna', 'salmon', 'anchovy', 'sardine', 'trout', 'chicken', 'duck', 'turkey', 'pork', 'ham', 'bacon', 'pancetta', 'prosciutto', 'sausage', 'lamb', 'veal', 'beef', 'oxtail', 'short-rib', 'meatball', 'bone-marrow', 'asparagus', 'pea', 'spinach', 'kale', 'broccoli', 'cauliflower', 'zucchini', 'eggplant', 'artichoke', 'leek', 'fennel', 'pumpkin', 'butternut', 'squash', 'corn', 'tomato', 'pepper', 'chili', 'garlic', 'onion', 'shallot', 'beetroot', 'carrot', 'parsnip', 'celeriac', 'celery', 'basil', 'sage', 'rosemary', 'thyme', 'mint', 'parsley', 'dill', 'saffron', 'paprika', 'curry', 'pesto', 'gorgonzola', 'parmesan', 'mozzarella', 'fontina', 'pecorino', 'ricotta', 'goat-cheese', 'blue-cheese', 'walnut', 'hazelnut', 'almond', 'pistachio', 'pine-nut', 'chestnut', 'lemon', 'guanciale', 'truffle-oil', 'porchetta', 'nduja', 'speck', 'mortadella', 'salsiccia', 'turnip'];
const dishNames = ['spaghetti', 'linguine', 'fettuccine', 'tagliatelle', 'pappardelle', 'bucatini', 'penne', 'rigatoni', 'ziti', 'paccheri', 'farfalle', 'fusilli', 'orecchiette', 'cavatelli', 'cavatappi', 'strozzapreti', 'trofie', 'bigoli', 'malloreddus', 'gnocchi', 'ravioli', 'tortellini', 'agnolotti', 'cannelloni', 'manicotti', 'mezzelune', 'culurgiones', 'ravioloni', 'tortelloni', 'cappelletti', 'lasagna', 'bake', 'gratin', 'casserole', 'timballo', 'parmigiana', 'polenta', 'farinata', 'crostata', 'torta', 'pizza', 'calzone', 'stromboli', 'focaccia', 'piadina', 'bruschetta', 'crostini', 'panzerotti', 'ciabatta', 'tigelle', 'gnocco-fritto', 'arancini', 'suppli', 'schiacciata', 'grissini', 'soup', 'stew', 'broth', 'minestrone', 'zuppa', 'bisque', 'chowder', 'ragout', 'ragu', 'goulash', 'salad', 'carpaccio', 'antipasto', 'panzanella', 'insalata', 'frittata', 'omelette', 'scramble', 'quiche', 'tortilla', 'pilaf', 'paella', 'fried-rice', 'rice-bowl', 'noodles', 'sandwich', 'panini', 'wrap', 'burger', 'flatbread', 'skillet', 'stir-fry', 'saute', 'grill', 'roast', 'kebab', 'skewers', 'fritters', 'croquettes', 'tempura', 'scaloppine', 'piccata', 'cacciatore', 'saltimbocca', 'braciola'];

const getRandElement = arr => {
    return arr[Math.floor(Math.random() * arr.length)];
}

const getRandMessage = () => {
    const dishStyle = getRandElement(dishStyles);
    const whatAdded = getRandElement(whatAddeds);
    const dishName = getRandElement(dishNames);
    const message = `Today's dish is ${dishStyle}-style ${whatAdded} ${dishName}.`;

    return message
}

console.log(getRandMessage());