const dishStyles = ['French', 'Spanish', 'Portuguese', 'Greek', 'Turkish', 'Moroccan', 'Tunisian', 'Egyptian', 'Lebanese', 'Syrian', 'Israeli', 'Persian', 'Georgian', 'Armenian', 'Azerbaijani', 'Russian', 'Ukrainian', 'Polish', 'Czech', 'Hungarian', 'Romanian', 'Bulgarian', 'Serbian', 'Croatian', 'Bosnian', 'Slovenian', 'Albanian', 'Macedonian', 'Swiss', 'Austrian', 'German', 'Belgian', 'Dutch', 'British', 'English', 'Scottish', 'Welsh', 'Irish', 'Scandinavian', 'Norwegian', 'Swedish', 'Danish', 'Finnish', 'Icelandic', 'Estonian', 'Indian', 'Lithuanian', 'Mediterranean', 'Balkan', 'Catalan', 'Basque', 'Andalusian', 'Tuscan', 'Roman', 'Neapolitan', 'Sicilian', 'Venetian', 'Ligurian', 'Piedmontese', 'Lombard', 'Calabrian', 'American', 'Californian', 'Texan', 'Tex-Mex', 'Southern', 'Cajun', 'Creole', 'Hawaiian', 'Mexican', 'Yucatecan', 'Oaxacan', 'Peruvian', 'Brazilian', 'Argentinian', 'Chilean', 'Colombian', 'Venezuelan', 'Ecuadorian', 'Uruguayan', 'Caribbean', 'Jamaican', 'Cuban', 'Dominican', 'Chinese', 'Cantonese', 'Sichuan', 'Hunan', 'Shanghainese', 'Taiwanese', 'Japanese', 'Okinawan', 'Korean', 'Thai', 'Vietnamese', 'Cambodian', 'Laotian', 'Malaysian', 'Singaporean', 'Indonesian'];
const whatAddeds = ['truffle', 'porcini', 'chanterelle', 'morel', 'shiitake', 'oyster', 'portobello', 'cremini', 'enoki', 'lobster', 'crab', 'shrimp', 'prawn', 'scallop', 'clam', 'mussel', 'octopus', 'squid', 'cuttlefish', 'tuna', 'salmon', 'anchovy', 'sardine', 'trout', 'chicken', 'duck', 'turkey', 'pork', 'ham', 'bacon', 'pancetta', 'prosciutto', 'sausage', 'lamb', 'veal', 'beef', 'oxtail', 'short-rib', 'meatball', 'bone-marrow', 'asparagus', 'pea', 'spinach', 'kale', 'broccoli', 'cauliflower', 'zucchini', 'eggplant', 'artichoke', 'leek', 'fennel', 'pumpkin', 'butternut', 'squash', 'corn', 'tomato', 'pepper', 'chili', 'garlic', 'onion', 'shallot', 'beetroot', 'carrot', 'parsnip', 'celeriac', 'celery', 'basil', 'sage', 'rosemary', 'thyme', 'mint', 'parsley', 'dill', 'saffron', 'paprika', 'curry', 'pesto', 'gorgonzola', 'parmesan', 'mozzarella', 'fontina', 'pecorino', 'ricotta', 'goat-cheese', 'blue-cheese', 'walnut', 'hazelnut', 'almond', 'pistachio', 'pine-nut', 'chestnut', 'lemon', 'guanciale', 'truffle-oil', 'porchetta', 'nduja', 'speck', 'mortadella', 'salsiccia', 'turnip'];
const dishNames = ['spaghetti', 'linguine', 'fettuccine', 'tagliatelle', 'pappardelle', 'bucatini', 'penne', 'rigatoni', 'ziti', 'paccheri', 'farfalle', 'fusilli', 'orecchiette', 'cavatelli', 'cavatappi', 'strozzapreti', 'trofie', 'bigoli', 'malloreddus', 'gnocchi', 'ravioli', 'tortellini', 'agnolotti', 'cannelloni', 'manicotti', 'mezzelune', 'culurgiones', 'ravioloni', 'tortelloni', 'cappelletti', 'lasagna', 'bake', 'gratin', 'casserole', 'timballo', 'parmigiana', 'polenta', 'farinata', 'crostata', 'torta', 'pizza', 'calzone', 'stromboli', 'focaccia', 'piadina', 'bruschetta', 'crostini', 'panzerotti', 'ciabatta', 'tigelle', 'gnocco-fritto', 'arancini', 'suppli', 'schiacciata', 'grissini', 'soup', 'stew', 'broth', 'minestrone', 'zuppa', 'bisque', 'chowder', 'ragout', 'ragu', 'goulash', 'salad', 'carpaccio', 'antipasto', 'panzanella', 'insalata', 'frittata', 'omelette', 'scramble', 'quiche', 'tortilla', 'pilaf', 'paella', 'fried-rice', 'rice-bowl', 'noodles', 'sandwich', 'panini', 'wrap', 'burger', 'flatbread', 'skillet', 'stir-fry', 'saute', 'grill', 'roast', 'kebab', 'skewers', 'fritters', 'croquettes', 'tempura', 'scaloppine', 'piccata', 'cacciatore', 'saltimbocca', 'braciola'];
const startNames = ['Forgotten', 'Hidden', 'Secret', 'Silent', 'Quiet', 'Mystic', 'Enchanted', 'Golden', 'Silver', 'Bronze', 'Copper', 'Rustic', 'Cozy', 'Warm', 'Merry', 'Jovial', 'Happy', 'Cheerful', 'Sunny', 'Starry', 'Moonlit', 'Lunar', 'Solar', 'Fiery', 'Smoky', 'Spiced', 'Savory', 'Saffron', 'Aromatic', 'Fragrant', 'Wild', 'Noble', 'Regal', 'Royal', 'Grand', 'Majestic', 'Ancient', 'Timeless', 'Vintage', 'Classic', 'Modern', 'Urban', 'Coastal', 'Seaside', 'Oceanic', 'Nautical', 'Windy', 'Breezy', 'Misty', 'Foggy', 'Rainy', 'Stormy', 'Frosty', 'Snowy', 'Icy', 'Crystal', 'Emerald', 'Ruby', 'Sapphire', 'Amber', 'Ivory', 'Velvet', 'Silken', 'Honeyed', 'Caramel', 'Gilded', 'Burnished', 'Charred', 'Woodfired', 'Hearthside', 'Fireside', 'Candlelit', 'Shadowed', 'Shaded', 'Sunlit', 'Autumnal', 'Wintry', 'Spring', 'Summer', 'Blooming', 'Flourishing', 'Lively', 'Vibrant', 'Luminous', 'Radiant', 'Glowing', 'Whispering', 'Wandering', 'Roaming', 'Secretive', 'Mellow', 'Tranquil', 'Serene', 'Peaceful', 'Gentle', 'Bold', 'Daring', 'Hearty', 'Zesty', 'Smoldering'];
const endNames = ['Harbor', 'House', 'Hill', 'Temple', 'Manor', 'Tavern', 'Bistro', 'Kitchen', 'Table', 'Hearth', 'Spoon', 'Fork', 'Knife', 'Plate', 'Bowl', 'Kettle', 'Cauldron', 'Skillet', 'Oven', 'Grill', 'Smokehouse', 'Mill', 'Barn', 'Cellar', 'Loft', 'Attic', 'Pantry', 'Market', 'Bazaar', 'Plaza', 'Court', 'Alley', 'Lane', 'Street', 'Corner', 'Crossing', 'Bridge', 'Gate', 'Tower', 'Castle', 'Keep', 'Citadel', 'Abbey', 'Chapel', 'Shrine', 'Garden', 'Grove', 'Orchard', 'Vineyard', 'Meadow', 'Field', 'Prairie', 'Valley', 'Canyon', 'Ridge', 'Peak', 'Summit', 'Mount', 'Cliffs', 'Shore', 'Coast', 'Beach', 'Bay', 'Cove', 'Dock', 'Wharf', 'Pier', 'Anchor', 'Compass', 'Lantern', 'Lighthouse', 'Sail', 'Ship', 'Cabin', 'Lodge', 'Inn', 'Hall', 'Parlor', 'Lounge', 'Terrace', 'Patio', 'Courtyard', 'Arcade', 'Gallery', 'Atrium', 'Fountain', 'Spring', 'Well', 'Brook', 'River', 'Lake', 'Lagoon', 'Marsh', 'Haven', 'Forest', 'Woods', 'Glade', 'Clearing', 'Camp', 'Outpost'];

const getRandElement = arr => {
    return arr[Math.floor(Math.random() * arr.length)];
}

const getRandMessage = () => {
    const dishStyle = getRandElement(dishStyles);
    const whatAdded = getRandElement(whatAddeds);
    const dishName = getRandElement(dishNames);
    const startName = getRandElement(startNames);
    const endName = getRandElement(endNames);

    const message = `
    Welcome to our restaurant ${startName} ${endName}.\n
    Today's dish is ${dishStyle}-style ${whatAdded} ${dishName}.
    `;

    return message
}

console.log(getRandMessage());